from __future__ import annotations

from datetime import datetime, timezone
from typing import List, Literal, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class AttackAttempt(BaseModel):
    """Single attempt generated by the attacker."""

    skill: str
    objective: str
    payload: str
    target_response: Optional[str] = None


class JudgeVerdict(BaseModel):
    """Result returned by the Judge after inspecting the target response."""

    is_vulnerable: bool
    reason: str
    severity: Literal["low", "medium", "high"] = "medium"


class AttackResult(BaseModel):
    """A full cycle result: attempt + verdict + timestamp."""

    attempt: AttackAttempt
    verdict: JudgeVerdict
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class AttackSession(BaseModel):
    """Container for a session against a target."""

    session_id: UUID = Field(default_factory=uuid4)
    target: str
    objective: str
    attempts: List[AttackResult] = Field(default_factory=list)

    def to_json(self) -> dict:
        return self.model_dump(mode="json")
